services: 
usuarios:
  build: ./microservicios/usuarios
  container_name: usuarios
  links:
    - db 
  ports:
  - "3001:3001"

productos:
  build: ./microservicios/productos
  container_name: productos
  links:
    - db
  ports:
    - "3002:3002"

ordenes:
  build: ./microservicios/ordenes
  container_name: ordenes
  links:
  - db
  - usuarios
  - productos
  ports:
  - "3003:3003"

web:
  build: ./web
  container_name: web
  links:
    - usuarios
    - productos
    - ordenes
  ports:
  -"8080:80"

db:
  image: mysql: 5.7
  container_name: db
  ports:
  "32000:3306"
  environment:
  MYSQL_ROOT_PASSWORD: root

volumes:
- ./db:/docker-entrypoint-initdb.d